### ISSUE TITLE
Only 4 servings of "Beverages" clickable on Galaxy S2 on version 11 of the app

### ISSUE THREAD

**Issue by AppleOatmeal** [nutritionfactsorg/daily-dozen-android#33]
In the latest version (10.3) of the app, only 4 servings of the group "Beverages" are clickable on a Galaxy S2 (latest Android updates). The fifth serving is out of the screen and unclickable, as shown in the picture. The picture shows the main screen scrolled down on my phone.

![screenshot_2016-10-17-18-34-05](https://cloud.githubusercontent.com/assets/22891293/19444401/f975973e-9498-11e6-80ad-087ce2caead8.png)

My main concern here is if this affects users on a larger scale. Maybe it only affects certain screen resolutions or small screen resolutions (the Galaxy S2 is 800 x 480 pixels).

Please let me know if there's anything I can do to help. Thanks for making this great app. :)

**Comment by slavick** [comment]
Thank you! I'm looking into it.

**Comment by AppleOatmeal** [comment]
Thank you, I forgot to mention that I'm running stock Android 4.1.2 (the latest for my phone).

**Comment by slavick** [comment]
I've just released a new version of the app with a fix for this issue. I tried to adjust margins and paddings in order to fit the checkbox, but I'm not sure if I was successful. When you get the update, can you please let me know if all 5 checkboxes can be seen? If the checkbox is not checkable, please reopen this issue.

Thanks

**Comment by AppleOatmeal** [comment]
Hi!

I updated to the latest version (version 11) and unfortunately the problem still exists.
Here's how the main screen looks now on my same phone.

![screenshot_2016-11-17-17-07-32](https://cloud.githubusercontent.com/assets/22891293/20396076/ad2ffd3e-aced-11e6-9046-15593689246c.png)

As can be seen, the screen looks a little bit different (better in my opinion), but still only 4 checkboxes can be accessed. I'm not sure if it's a new feature or a bug, but when the first serving is checked, it checks all servings. If it's a new feature, I think it is pretty cool. :) Anyway, with that feature/bug, all 5 servings can be checked (although you cannot uncheck the fifth serving once checked the first time). So it's possible now to check all servings, although the original problem still exists.

Also, I believe I can't reopen the issue, perhaps you could do that?

**Comment by slavick** [comment]
I was afraid my changes might not have been enough. I tried to simulate the smallest display size using the new display size feature in Nougat, but clearly it wasn't accurate. I will reopen the issue and probably have to create a new layout for small display sizes.

And yes, checking multiple checkboxes is much quicker in the latest app.

Thanks

**Comment by AppleOatmeal** [comment]
I understand. Please let me know if there's anything I can do to help solve the problem.

Thank you for keeping working on the app. :)

**Comment by slavick** [comment]
The v12 release of Daily Dozen should fix this issue for good. The food name is now above the checkboxes instead of being fit horizontally inline with them.
